#!/usr/bin/perl
# Clears the chat flag for the specified node

use strict;
use warnings;

my $OutputFile = "/var/www/html/chats/chatreq.txt";	# Where we put our chat requests

# === No changes below here

my @PageLines;
my @PageLinesOutput;
my $CurLine="";
# Read in existing file if it exists
if (! -f $OutputFile)
{
	print("---No nodes requesting chat --- Press RETURN\n");
	my $UserInput = <STDIN>;
	exit 0;
}

# Read in node to clear
print "What node should I clear?\n";
my $UserInput = <STDIN>;
chop($UserInput);
if ($UserInput eq "")
{
	print("You need to specify the user's node to clear\n");
	exit 1;
}

#print "Clearing '$UserInput'\n";

open my $handle, '<', $OutputFile;
chomp(@PageLines = <$handle>);
close $handle;

# Now look if we are already paging this user
foreach $CurLine (@PageLines)
{
	my ($CurUserInput, $CurUserName, $CurUserDate) = split('	', $CurLine);
	if ($UserInput ne $CurUserInput)
	{
		push (@PageLinesOutput, $CurLine);
	}
}

# Save array to file
open my $outhandle, '>', $OutputFile || die "Unable to open output file for writing";
foreach $CurLine (@PageLinesOutput)
{
	print($outhandle "$CurLine\n");
}
close ($outhandle);
if ((scalar @PageLinesOutput == 0) && (-f $OutputFile))
{
	unlink($OutputFile);
}
exit 0;
