#!/usr/bin/perl
# Clears the chat flag for the specified node

use strict;
use warnings;

my $OutputFile = "/var/www/html/chatreq.txt";	# Where we put our chat requests

# === No changes below here

my @PageLines;
my @PageLinesOutput;
my $CurLine="";

print "What node should I clear?\n";

my $UserInput = <STDIN>;
#my $UserInput = "1";

#chop($UserInput);

if ($UserInput eq "")
{
	print("You need to specify the user's node to clear\n");
	exit 1;
}

#print "Clearing '$UserInput'\n";

# Read in existing file if it exists
if (! -f $OutputFile)
{
	print("No nodes requesting chat\n");
	exit 0;
}
open my $handle, '<', $OutputFile;
chomp(@PageLines = <$handle>);
close $handle;

# Now look if we are already paging this user
print "Saw this: @PageLines\n";
foreach $CurLine (@PageLines)
{
print "Loop: $CurLine\n";
	my ($CurUserInput, $CurUserName, $CurUserDate) = split('	', $CurLine);
print "Saw $CurUserInput\n";
	if ($UserInput ne $CurUserInput)
	{
print "Pushed $CurLine\n";
		push (@PageLinesOutput, $CurLine);
	}
}

# Save array to file
open my $outhandle, '>', $OutputFile || die "Unable to open output file for writing";
foreach (@PageLinesOutput)
{
	#print "Saving $_\n";
	print($outhandle "$_\n");
}
close ($outhandle);
if ((scalar @PageLinesOutput == 0) && (-f $OutputFile))
{
	#print "Wanting to remove file\n";
	unlink($OutputFile);
}
exit 0;
