#!/usr/bin/perl
# Clears the chat flag for the specified node

use strict;
use warnings;

my $OutputFile = "/var/www/html/chatreq.txt";	# Where we put our chat requests

# === No changes below here

my @PageLines;
my @PageLinesOutput;

print "What node should I clear?\n";

my $UserInput = <STDIN>;

chop($UserInput);

if ($UserInput eq "")
{
	print("You need to specify the user's node to clear\n");
	exit 1;
}

# Read in existing file if it exists
if (-f $OutputFile)
{
	open my $inhandle, '<', $OutputFile || die "Unable to open output file for reading";
	chomp(@PageLines = <$inhandle>);
	close $inhandle;
}

# Now look if we are already paging this user

foreach (@PageLines)
{
	my ($CurUserInput, $CurUserName, $CurUserDate) = split('	', $_);
	if ($UserInput ne $CurUserInput)
	{
		push (@PageLinesOutput, $_);
		last;
	}
}

# Save array to file
open my $outhandle, '>', $OutputFile || die "Unable to open output file for writing";
foreach (@PageLinesOutput)
{
	#print "Saving $_\n";
	print($outhandle "$_\n");
}
close ($outhandle);
if ((scalar @PageLinesOutput == 0) && (-f $OutputFile))
{
	#print "Wanting to remove file\n";
	unlink($OutputFile);
}
exit 0;
