#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $SYNCPAGERDIR = "/home/marisa/Documents/SyncPager";

# No changes below here...

my $running=`ps ax|grep "./SyncPager"|grep -v grep`;

# check if SyncPager process is running
if ($running ne "")
{
	print ("Startupscript already running...\n");
	exit (0);
}

while (-1)
{
	chdir $SYNCPAGERDIR;
	# check if Sync Pager process is running
	$running=`ps ax|grep "./SyncPager"|grep -v grep`;
	if ($running eq "")
	{
		print "Sync Pager not running\n";
		# See if they want the server started
		if (! -f "$SYNCPAGERDIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="Sync Pager Down, Restarting: $datestring";
			open(OUTF, ">>$SYNCPAGERDIR/SyncPager.log") || die "Unable to open $SYNCPAGERDIR/SyncPager.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir "$SYNCPAGERDIR";
			print "Starting screen process\n";
			system("/usr/bin/screen -fa -S SyncPager -d -U -m ./SyncPager");
		}
	}
	else
	{
		print "Sync Pager already running\n";
	}
	# Sleep for 1 minute before checking again
	sleep(60);
}
exit(0);
