#!/usr/bin/perl

# This tool alerts the BBS sysop if they are being paged

use strict;
use warnings;
use Email::Simple;
use Email::Simple::Creator;
use Email::Sender::Simple qw(sendmail);
use LWP::Simple;

# No changes below here
my $CurHost="";
my $CurPort=0;
my $CurId=0;
my $CurStatus="";
my $timeout=5;
my $VERSION="1.0";
my $dbh;
my $CONF_FILE="config.ini";
my $EMAIL_SUBJ="";
my $EMAIL_FROM="";
my $CurNotify="";
my $email="";
my $CHECK_URL="";
my $text="";

# Read in configuration options
open(CONF, "<$CONF_FILE") || die("Unable to read config file '$CONF_FILE'");
while(<CONF>)
{
	chop;
	my ($FIELD_TYPE, $FIELD_VALUE) = split (/	/, $_);
	# print("Type is $FIELD_TYPE\n");
	if ($FIELD_TYPE eq "Email_Subj")
	{
		$EMAIL_SUBJ = $FIELD_VALUE;
	}
	elsif ($FIELD_TYPE eq "Email_From")
	{
		$EMAIL_FROM = $FIELD_VALUE;
	}
	elsif ($FIELD_TYPE eq "CheckURL")
	{
		$CHECK_URL = $FIELD_VALUE;
	}
}
close(CONF);

if ($EMAIL_SUBJ eq "")
{
	print "You have not set a email subject in $CONF_FILE\n";
	exit 1;
}
if ($EMAIL_FROM eq "")
{
	print "You have not set a email sender in $CONF_FILE\n";
	exit 1;
}
if ($CHECK_URL eq "")
{
	print "You have not set a URL to check in $CONF_FILE\n";
	exit 1;
}

# Marks the MUD state and check time
sub MarkMUD
{
	my($day, $month, $year)=(localtime)[3,4,5];
	$year += 1900;
	$month += 1;
	$month = substr("0".$month, -2);
	$day = substr("0".$day, -2);
	my $timeString="$year-$month-$day";
	# Field5 = date in "0000-00-00"
	# Field6 = status in "Active/Unreachable" format
	# Should we send owner a note?
	if (($CurStatus eq "Unreachable") && ($CurNotify ne ""))
	{
		my $CurBody = <<"END_MESSAGE_BODY";
Dear $CurNotify,
 
At our last scan of your MUD we could not connect to it. You may want to look into it or disable notifications if you don't want to get these messages in the future.

Next check will be in roughly 6 hours.
 
Regards,
The Admins at PocketMUD
END_MESSAGE_BODY
		$email = Email::Simple->create(
		header => [
		       From => $EMAIL_FROM,
		       To => $CurNotify,
		       Subject => $EMAIL_SUBJ,
		],
		body => $CurBody);
		sendmail($email);
	}
}

print("Checking for Sysop Page Requests ($VERSION)\n");
print("===============================================\n");
print "Working on '$CHECK_URL'\n";

$text = get($CHECK_URL);
open(FILENAME, '<', \$text);
while(<FILENAME>)
{
	chop();
	print ("Line = '$_'\n");
}
exit(0);
